import type * as React from "react";
import {
  Award,
  Baby,
  BadgeDollarSign,
  Banknote,
  BarChart3,
  Bell,
  BookOpen,
  Briefcase,
  Building2,
  Bus,
  Calculator,
  Calendar,
  Car,
  Clapperboard,
  Clock,
  Coins,
  Coffee,
  CreditCard,
  Dices,
  Dumbbell,
  Ellipsis,
  Eye,
  FileText,
  Flame,
  Fuel,
  Gift,
  GraduationCap,
  HandCoins,
  HeartPulse,
  Home,
  Inbox,
  Landmark,
  LineChart,
  PiggyBank,
  Plane,
  Receipt,
  RotateCcw,
  Scale,
  Shapes,
  Shield,
  ShieldCheck,
  ShoppingBag,
  Shirt,
  Smartphone,
  Star,
  Stethoscope,
  Tag,
  Target,
  Ticket,
  TrendingUp,
  Utensils,
  UtensilsCrossed,
  Wallet,
  Wifi,
  Zap,
} from "lucide-react";

export type IconComponent = React.ComponentType<{
  className?: string;
  size?: number | string;
  strokeWidth?: number;
}>;

/**
 * Curated, serialisable set of icons that users can assign to categories and
 * accounts. Categories persist the icon *name* (a string), which is resolved
 * back to a component here.
 */
export const ICON_REGISTRY: Record<string, IconComponent> = {
  Wallet,
  Banknote,
  CreditCard,
  Coins,
  PiggyBank,
  Landmark,
  Building2,
  HandCoins,
  BadgeDollarSign,
  Tag,
  Receipt,
  Calculator,
  Scale,
  Briefcase,
  Award,
  Ticket,
  Dices,
  Gift,
  RotateCcw,
  Home,
  ShoppingBag,
  Shirt,
  Smartphone,
  Clapperboard,
  Utensils,
  UtensilsCrossed,
  Coffee,
  Baby,
  GraduationCap,
  BookOpen,
  HeartPulse,
  Stethoscope,
  Dumbbell,
  Bus,
  Car,
  Fuel,
  Plane,
  Wifi,
  Zap,
  Flame,
  Shield,
  ShieldCheck,
  Bell,
  Clock,
  Calendar,
  TrendingUp,
  BarChart3,
  LineChart,
  Target,
  Star,
  Eye,
  FileText,
  Inbox,
  Shapes,
  Ellipsis,
};

export const ICON_NAMES = Object.keys(ICON_REGISTRY);

export function getIcon(name: string | null | undefined): IconComponent {
  if (name && ICON_REGISTRY[name]) return ICON_REGISTRY[name];
  return Tag;
}
